libname regress "D:\SAS\regression_analysis\workspace";
options nodate nonumber FORMCHAR="|----|+|---+=|-/\<>*";

data dataset;
	set regress.group_project_data_interact; 
run;

%macro regress(label);
	proc reg data=dataset plots=none;
		model score = &label;
	run;
	quit;
%mend;

%regress(grade_gender); 
%regress(grade_interest); 
%regress(grade_favor); 
%regress(grade_chinese); 
%regress(grade_patience); 
%regress(grade_extras); 
%regress(grade_study_hours); 
%regress(grade_work_hours); 
%regress(grade_club_hours); 
%regress(grade_sleep_hours); 
%regress(grade_commute_hours); 
%regress(gender_interest); 
%regress(gender_favor); 
%regress(gender_chinese); 
%regress(gender_patience); 
%regress(gender_extras); 
%regress(gender_study_hours); 
%regress(gender_work_hours); 
%regress(gender_club_hours); 
%regress(gender_sleep_hours); 
%regress(gender_commute_hours); 
%regress(interest_favor); 
%regress(interest_chinese); 
%regress(interest_patience); 
%regress(interest_extras); 
%regress(interest_study_hours); 
%regress(interest_work_hours); 
%regress(interest_club_hours); 
%regress(interest_sleep_hours); 
%regress(interest_commute_hours); 
%regress(favor_chinese); 
%regress(favor_patience); 
%regress(favor_extras); 
%regress(favor_study_hours); 
%regress(favor_work_hours); 
%regress(favor_club_hours); 
%regress(favor_sleep_hours); 
%regress(favor_commute_hours); 
%regress(chinese_patience); 
%regress(chinese_extras); 
%regress(chinese_study_hours); 
%regress(chinese_work_hours); 
%regress(chinese_club_hours); 
%regress(chinese_sleep_hours); 
%regress(chinese_commute_hours); 
%regress(patience_extras); 
%regress(patience_study_hours); 
%regress(patience_work_hours); 
%regress(patience_club_hours); 
%regress(patience_sleep_hours); 
%regress(patience_commute_hours); 
%regress(extras_study_hours); 
%regress(extras_work_hours); 
%regress(extras_club_hours); 
%regress(extras_sleep_hours); 
%regress(extras_commute_hours); 
%regress(study_hours_work_hours); 
%regress(study_hours_club_hours); 
%regress(study_hours_sleep_hours); 
%regress(study_hours_commute_hours); 
%regress(work_hours_club_hours); 
%regress(work_hours_sleep_hours); 
%regress(work_hours_commute_hours); 
%regress(club_hours_sleep_hours); 
%regress(club_hours_commute_hours); 
%regress(sleep_hours_commute_hours);
